import Fuse from './third_party/fuse/7.5.0/fuse.min.mjs';
import { extractIssns, isValidIssn, normalizeIssn } from './src/issn.js';
import { emptyProfile } from './src/schema.js';
import { reconcile } from './src/reconcile.js';
import { lookupDoaj, lookupOpenAlex, lookupCrossref, lookupPlantWorks } from './src/evidence.js';
import { buildEvidenceClaims, statusExplanation } from './src/explain.js';
import { dossierFilename, dossierJson } from './src/export.js';
import { createCache } from './src/cache.js';
import { downloadText } from '../_shared/js/download.js';
import { safeTextElement } from '../_shared/js/dom.js';
import { safeUrl } from '../_shared/js/safe-url.js';

const $ = id => document.getElementById(id);
const query = $('journal-query'), suggestions = $('suggestions'), status = $('status');
const cache = createCache(); let seed = [], fuse, selected = null, profile = null, timer, activeSuggestion = -1;
const checklistLabels = ['Editorial board identities and affiliations checked on institutional pages', 'Peer-review process and timeline claims checked', 'Current fees, taxes, waivers, and refund policy checked', 'Contact email domain matches the journal or publisher domain', 'Archiving and preservation policy checked at the named service', 'Publication ethics, corrections, and retractions policy checked'];

const text = (tag, value, className) => safeTextElement(document, tag, value, className);
const external = (label, href) => { const url = safeUrl(href); if (!url) return text('span', label); const a = text('a', label); a.href = url; a.target = '_blank'; a.rel = 'noopener noreferrer'; return a; };
const format = value => value == null || value === '' ? 'Not reported' : Array.isArray(value) ? (value.length ? value.join(' · ') : 'Not reported') : typeof value === 'object' ? Object.entries(value).filter(([,v]) => v != null).map(([k,v]) => `${k.replace(/([A-Z])/g,' $1')}: ${Array.isArray(v) ? JSON.stringify(v) : v}`).join(' · ') || 'Not reported' : value === true ? 'Yes' : value === false ? 'No' : String(value);

async function init() {
  try { seed = await fetch('./data/journal-seed.min.json').then(r => { if (!r.ok) throw new Error('seed unavailable'); return r.json(); }); fuse = new Fuse(seed, { keys: [{name:'title',weight:.75},{name:'issns',weight:.25}], threshold:.34, ignoreLocation:true, minMatchCharLength:2, includeScore:true }); status.textContent = `${seed.length.toLocaleString()} journal records ready for local search.`; } catch { status.textContent = 'Local suggestions are unavailable. You can still enter a valid ISSN for live lookup.'; }
  renderChecklist(); const params = new URLSearchParams(location.search); if (params.get('q')) { query.value = params.get('q'); showSuggestions(); }
}
function showSuggestions() {
  clearTimeout(timer); timer = setTimeout(() => {
    const value = query.value.trim(); suggestions.replaceChildren(); selected = null; activeSuggestion = -1; query.removeAttribute('aria-activedescendant');
    if (!fuse || value.length < 2) return;
    fuse.search(value, { limit: 8 }).forEach(({item}, index) => { const button = document.createElement('button'); button.type = 'button'; button.id = `journal-suggestion-${index}`; button.className = 'suggestion'; button.setAttribute('role','option'); button.setAttribute('aria-selected','false'); const label = document.createElement('span'); label.append(text('strong',item.title), text('small',[item.category, item.issns.join(' · ')].filter(Boolean).join(' · '))); button.append(label,text('span',`Q${item.quartile}`,'quartile')); button.onclick = () => chooseSuggestion(item); suggestions.append(button); });
  }, 120);
}
function chooseSuggestion(item) { selected = item; query.value = item.issns[0] || item.title; suggestions.replaceChildren(); activeSuggestion = -1; query.removeAttribute('aria-activedescendant'); status.textContent = `${item.title} selected from the local smbajwa.com source.`; }
function setActiveSuggestion(index) { const options = [...suggestions.querySelectorAll('[role="option"]')]; if (!options.length) return; activeSuggestion = Math.max(0, Math.min(index, options.length - 1)); options.forEach((option, i) => option.setAttribute('aria-selected', String(i === activeSuggestion))); query.setAttribute('aria-activedescendant', options[activeSuggestion].id); options[activeSuggestion].scrollIntoView({ block: 'nearest' }); }
async function cached(name, key, task) { const cacheKey = `${name}:${key}`; const prior = cache.get(cacheKey); if (prior) return { value: prior, cached: true }; const value = await task(); if (value) cache.set(cacheKey, value); return { value, cached: false }; }
async function lookup() {
  const entered = query.value.trim(); if (!entered) { status.textContent = 'Enter a journal title or ISSN.'; query.focus(); return; }
  const issnMatches = extractIssns(entered); const issn = selected?.issns?.[0] || issnMatches[0] || ''; const title = selected?.title || (!issn ? entered : '');
  if (issn && !isValidIssn(issn)) { status.textContent = `${normalizeIssn(issn)} does not pass the ISSN checksum.`; return; }
  if (!confirm(`This lookup sends only ${issn || title} to DOAJ, OpenAlex, and Crossref. Continue?`)) return;
  $('lookup').disabled = true; status.textContent = 'Requesting public metadata from DOAJ, OpenAlex, and Crossref…';
  const key = issn || title.toLowerCase(); const tasks = [ ['DOAJ', () => lookupDoaj({issn,title})], ['OpenAlex', () => lookupOpenAlex({issn,title})], ['Crossref', () => lookupCrossref({issn,title})], ['OpenAlex works', () => lookupPlantWorks({issn,title})] ];
  const settled = await Promise.allSettled(tasks.map(([name, task]) => cached(name,key,task)));
  const records = settled.slice(0,3).map(x => x.status === 'fulfilled' ? x.value.value : null).filter(Boolean); const works = settled[3].status === 'fulfilled' ? settled[3].value.value : [];
  const failures = settled.map((x,i) => x.status === 'rejected' ? `${tasks[i][0]}: ${x.reason.message}` : null).filter(Boolean);
  profile = emptyProfile({ entered, issns: issn ? [issn] : [], title, localSelection: selected }); const merged = reconcile(records, profile.query); profile.identity = merged.identity; profile.claims = [...merged.claims, ...buildEvidenceClaims(records, works)]; profile.conflicts = merged.conflicts; profile.works = works; profile.sources = records.map(r => ({source:r.source,url:r.url,retrievedAt:r.retrievedAt})); profile.errors = failures; profile.checklist = readChecklist();
  renderProfile(); $('lookup').disabled = false; const cacheCount = settled.filter(x => x.status === 'fulfilled' && x.value.cached).length; status.textContent = `Profile built from ${records.length} source response${records.length===1?'':'s'}${cacheCount ? ` (${cacheCount} cached)` : ''}.${failures.length ? ` ${failures.length} request${failures.length===1?'':'s'} could not be completed.` : ''}`;
}
function renderProfile() {
  $('profile').classList.remove('hidden'); $('profile-title').textContent = profile.identity.title || profile.query.title || profile.query.entered; $('profile-meta').textContent = `Generated ${new Date(profile.generatedAt).toLocaleString()} · ${profile.identity.issns?.join(' · ') || 'ISSN not returned'}`;
  const identities = [['ISSNs',profile.identity.issns],['Publisher',profile.identity.publishers],['Local source',profile.query.localSelection ? `${profile.query.localSelection.category} · Q${profile.query.localSelection.quartile}` : null]]; $('identity').replaceChildren(...identities.map(([label,value]) => { const card = document.createElement('div'); card.className='identity-card'; card.append(text('span',label),text('strong',format(value))); return card; }));
  if (profile.conflicts.length) { $('conflicts').classList.remove('hidden'); $('conflicts').replaceChildren(text('h3','Identity conflict requires review'), ...profile.conflicts.map(x=>text('p',x))); } else $('conflicts').classList.add('hidden');
  $('claims').replaceChildren(...profile.claims.map(renderClaim)); $('works').replaceChildren(...(profile.works.length ? profile.works.map(renderWork) : [text('p','No plant-related examples were returned. This does not establish that the journal is outside plant science.','empty-state')]));
  const links = $('source-links-list'); links.replaceChildren(...profile.sources.map(s => external(`Open ${s.source}`,s.url))); syncUrl(); $('profile').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
}
function renderClaim(c) { const card=document.createElement('article'); card.className='claim'; const head=document.createElement('header'); head.append(text('h4',c.label),text('span',c.status,`status-pill ${c.status.replaceAll(' ','-')}`)); card.append(head,text('p',format(c.value),'claim-value')); if(c.note) card.append(text('p',c.note,'claim-note')); const details=document.createElement('details'); const summary=text('summary',`${c.evidence.length} source record${c.evidence.length===1?'':'s'} · what this status means`); details.append(summary,text('p',statusExplanation(c.status))); c.evidence.forEach(e=>{ const p=document.createElement('p'); p.append(external(e.source,e.url),` · retrieved ${new Date(e.retrievedAt).toLocaleString()} · ${format(e.value)}`); details.append(p); }); card.append(details); return card; }
function renderWork(work) { const card=document.createElement('article'); card.className='work'; const h=text('h4',work.title); if(work.url) { const a=external(work.title,work.url); h.replaceChildren(a); } card.append(h,text('p',[work.year, ...(work.topics||[])].filter(Boolean).join(' · '))); return card; }
function renderChecklist() { const root=$('checklist-items'); root.replaceChildren(...checklistLabels.map((label,i)=>{ const row=document.createElement('div'); row.className='check-row'; const checkLabel=document.createElement('label'), box=document.createElement('input'); box.type='checkbox'; box.dataset.check=i; const note=document.createElement('input'); note.type='text'; note.placeholder='Optional note or URL'; note.setAttribute('aria-label',`${label} note`); note.dataset.note=i; checkLabel.append(box,document.createTextNode(label)); [box,note].forEach(el=>el.addEventListener('input',saveChecklist)); row.append(checkLabel,note); return row; })); try { const saved=JSON.parse(sessionStorage.getItem('journal-trust-checklist')||'{}'); checklistLabels.forEach((_,i)=>{ root.querySelector(`[data-check="${i}"]`).checked=Boolean(saved[i]?.checked); root.querySelector(`[data-note="${i}"]`).value=saved[i]?.note||''; }); } catch {} }
function readChecklist(){ return Object.fromEntries(checklistLabels.map((label,i)=>[label,{checked:document.querySelector(`[data-check="${i}"]`)?.checked||false,note:document.querySelector(`[data-note="${i}"]`)?.value||''}])); }
function saveChecklist(){ const compact=Object.fromEntries(checklistLabels.map((_,i)=>[i,{checked:document.querySelector(`[data-check="${i}"]`).checked,note:document.querySelector(`[data-note="${i}"]`).value}])); try{sessionStorage.setItem('journal-trust-checklist',JSON.stringify(compact));}catch{} if(profile)profile.checklist=readChecklist(); }
function syncUrl(){const u=new URL(location.href);u.search='';u.searchParams.set('q',profile.query.entered);history.replaceState(null,'',u)}
query.addEventListener('input',showSuggestions); query.addEventListener('keydown',e=>{const options=[...suggestions.querySelectorAll('[role="option"]')];if(e.key==='ArrowDown'&&options.length){e.preventDefault();setActiveSuggestion(activeSuggestion+1)}else if(e.key==='ArrowUp'&&options.length){e.preventDefault();setActiveSuggestion(activeSuggestion<0?options.length-1:activeSuggestion-1)}else if(e.key==='Home'&&options.length){e.preventDefault();setActiveSuggestion(0)}else if(e.key==='End'&&options.length){e.preventDefault();setActiveSuggestion(options.length-1)}else if(e.key==='Enter'&&activeSuggestion>=0&&options[activeSuggestion]){e.preventDefault();options[activeSuggestion].click()}else if(e.key==='Enter'){lookup()}else if(e.key==='Escape'&&options.length){e.preventDefault();suggestions.replaceChildren();activeSuggestion=-1;query.removeAttribute('aria-activedescendant')}}); $('lookup').onclick=lookup; $('clear').onclick=()=>{query.value='';selected=null;activeSuggestion=-1;suggestions.replaceChildren();query.removeAttribute('aria-activedescendant');$('profile').classList.add('hidden');status.textContent='';history.replaceState(null,'',location.pathname);query.focus()}; $('clear-cache').onclick=()=>{cache.clear();status.textContent='Cached API responses cleared.'}; $('download').onclick=()=>{profile.checklist=readChecklist();downloadText(dossierFilename(profile),dossierJson(profile),'application/json;charset=utf-8')}; $('print').onclick=()=>window.print(); init();
