import {solveDilution,serialDilution} from './src/dilution-core.js?v=20';
import {analyseQpcr} from './src/qpcr-core.js?v=20';
import {transformSequence} from './src/sequence-core.js?v=20';
import {molarityFromMass,massForMolarity} from './src/molarity.js?v=20';
import {wallace,nearestNeighbor} from './src/tm.js?v=20';
import {parseCsv,setupLocalFileInput} from '../_shared/js/file-input.js?v=20';
import {downloadText} from '../_shared/js/download.js?v=20';
import {safeTextElement} from '../_shared/js/dom.js?v=20';
const $=id=>document.getElementById(id),fmt=x=>Number(x).toLocaleString(undefined,{maximumSignificantDigits:8});let qpcrResults=[],sequenceResults=[];
const text=(tag,value)=>safeTextElement(document,tag,value);
function fail(id,error){$(id).replaceChildren(text('p',String(error?.message||error)))}
function table(headers,rows){const table=document.createElement('table'),thead=document.createElement('thead'),tr=document.createElement('tr');headers.forEach(v=>tr.append(text('th',v)));thead.append(tr);const tbody=document.createElement('tbody');rows.forEach(row=>{const line=document.createElement('tr');row.forEach(v=>line.append(text('td',v)));tbody.append(line)});table.append(thead,tbody);return table}
const tabs=[...document.querySelectorAll('[role="tab"]')];
function activate(tab,{focus=false,update=true}={}){tabs.forEach(x=>{const active=x===tab;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active));x.tabIndex=active?0:-1;$(x.dataset.tab).hidden=!active;$(x.dataset.tab).classList.toggle('active',active)});if(update){const url=new URL(location.href);url.searchParams.set('tab',tab.dataset.tab);history.replaceState(null,'',`${url.pathname}${url.search}${url.hash}`)}if(focus)tab.focus()}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();activate(tabs[next],{focus:true})})});
const requested=new URLSearchParams(location.search).get('tab')||location.hash.slice(1),initial=tabs.find(x=>x.dataset.tab===requested);if(initial)activate(initial,{update:false});
function runDilution(){try{const input={};for(const key of ['c1','v1','c2','v2']){input[key]=$(key).value===''?null:Number($(key).value);input[`${key}Unit`]=$(`${key}-unit`).value}const r=solveDilution(input),unit=input[`${r.unknown}Unit`];$('dilution-result').replaceChildren(text('p',`${r.unknown.toUpperCase()} = ${fmt(r.value)} ${unit}${r.diluent===null?'':`; add ${fmt(r.diluent)} ${input.v2Unit} diluent`}`))}catch(error){fail('dilution-result',error)}}
$('dilution-form').addEventListener('submit',event=>{event.preventDefault();runDilution()});
$('serial-form').addEventListener('submit',event=>{event.preventDefault();try{const rows=serialDilution({factor:$('factor').value,steps:Number($('steps').value),finalVolume:$('final-volume').value});$('serial-result').replaceChildren(table(['Step','Relative concentration','Transfer (µL)','Diluent (µL)'],rows.map(r=>[r.step,fmt(r.relative),fmt(r.transfer),fmt(r.diluent)])))}catch(error){fail('serial-result',error)}});
const molarityForm=$('molarity-form');molarityForm.querySelectorAll('[name=mode]').forEach(input=>input.addEventListener('change',()=>{const toMass=input.checked&&input.value==='toMass';molarityForm.querySelector('.mass-input').hidden=toMass;molarityForm.querySelector('.molarity-input').hidden=!toMass}));molarityForm.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.target),mode=form.get('mode'),keys=mode==='fromMass'?['mass','molecularWeight','volume','purityPercent','hydrateFactor']:['molarity','molecularWeight','volume','purityPercent','hydrateFactor'],input=Object.fromEntries(keys.map(key=>[key,+form.get(key)]));input.volumePrefix=form.get('volumePrefix');input.massPrefix=form.get('massPrefix');try{const r=mode==='fromMass'?molarityFromMass(input):massForMolarity(input);$('molarity-result').replaceChildren(text('p',mode==='fromMass'?`Molarity = ${fmt(r.molarity)} mol/L; amount = ${fmt(r.moles)} mol.`:`Required mass = ${fmt(r.grams)} g; amount = ${fmt(r.moles)} mol.`))}catch(error){fail('molarity-result',error)}});
const rowsFromText=value=>parseCsv(value).slice(1).map(r=>[r[0],r[1],r[2],r[3]]);
function runQpcr(){try{qpcrResults=analyseQpcr(rowsFromText($('qpcr-data').value),{target:$('target').value.trim(),reference:$('reference').value.trim(),control:$('control').value.trim(),mode:$('mode').value,targetEfficiency:Number($('te').value),referenceEfficiency:Number($('re').value)});$('qpcr-result').replaceChildren(table(['Sample','Group','Mean target Ct','ΔCt','ΔΔCt','Fold','Flags'],qpcrResults.map(r=>r.error?[r.sample,r.group,'—','—','—','—',r.error]:[r.sample,r.group,r.targetMean.toFixed(3),r.delta.toFixed(3),r.ddCt.toFixed(3),r.fold.toFixed(4),[r.replicateWarning?'Replicate SD > 0.5':'',...r.warnings].filter(Boolean).join('; ')||'OK'])))}catch(error){fail('qpcr-result',error)}}
$('qpcr-form').addEventListener('submit',event=>{event.preventDefault();runQpcr()});setupLocalFileInput({input:$('qpcr-file'),status:$('file-status'),extensions:['csv'],maxRows:5000,onRead:r=>{$('qpcr-data').value=r.text;runQpcr()}});$('qpcr-download').addEventListener('click',()=>{const head='sample,group,mean_target_ct,delta_ct,delta_delta_ct,fold_change,propagated_se,propagated_fold_sd',lines=qpcrResults.filter(x=>!x.error).map(x=>[x.sample,x.group,x.targetMean,x.delta,x.ddCt,x.fold,x.se,x.sdFold].join(','));downloadText('plant-lab-qpcr-results.csv',[head,...lines].join('\r\n')+'\r\n','text/csv')});
$('sequence-form').addEventListener('submit',event=>{event.preventDefault();try{const r=transformSequence($('sequence-data').value,{rna:new FormData(event.target).get('alphabet')==='rna'}),operation=$('sequence-operation').value,out=document.createDocumentFragment();sequenceResults=r.records;r.records.forEach(record=>{out.append(text('h3',record.name),text('p',`Length ${record.length}; GC ${fmt(record.gc)}%`),text('pre',record[operation]))});$('sequence-result').replaceChildren(out)}catch(error){sequenceResults=[];fail('sequence-result',error)}});
$('sequence-download').addEventListener('click',()=>{const operation=$('sequence-operation').value;if(!sequenceResults.length)return fail('sequence-result','Transform a sequence before downloading.');const fasta=sequenceResults.map(record=>`>${record.name} ${operation}\n${record[operation]}`).join('\n')+'\n';downloadText('plant-lab-sequences.fasta',fasta,'text/x-fasta')});
$('tm-form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.target),input={sequence:form.get('sequence'),method:form.get('method'),sodiumMm:+form.get('sodiumMm'),primerNm:+form.get('primerNm'),selfComplementary:form.has('selfComplementary')};try{const r=input.method==='wallace'?wallace(input.sequence):nearestNeighbor(input.sequence,input);$('tm-result').replaceChildren(text('p',`Tm = ${fmt(r.tm)} °C; length ${r.length} nt; GC ${fmt(r.gcPercent)}%; ${r.method}.`))}catch(error){fail('tm-result',error)}});
function loadExample(tab){if(tab==='dilution'){Object.assign($('c1'),{value:100});$('v1').value='';$('c2').value=10;$('v2').value=50;runDilution()}else if(tab==='qpcr'){$('qpcr-data').value='sample,group,gene,Ct\nC1,control,target,20.0\nC1,control,target,20.2\nC1,control,ref,18.0\nC1,control,ref,18.2\nT1,treated,target,18.0\nT1,treated,target,18.2\nT1,treated,ref,18.0\nT1,treated,ref,18.2';runQpcr()}else{$('sequence-data').value='>example\nARYN';$('sequence-form').requestSubmit()}}
if(new URLSearchParams(location.search).get('example')==='1')loadExample((initial||tabs[0]).dataset.tab);
$('clear').addEventListener('click',()=>{const active=tabs.find(x=>x.getAttribute('aria-selected')==='true').dataset.tab,$panel=$(active);$panel.querySelectorAll('form').forEach(form=>form.reset());$panel.querySelectorAll('.result').forEach(result=>result.replaceChildren())});
