import {detectIdentifiers} from '../identifier-toolkit/src/detect.js?v=14';
import {parseInput} from '../reference-checker/src/parse.js?v=14';
import {findDuplicates} from '../reference-checker/src/duplicates.js?v=14';
import {safeTextElement} from '../_shared/js/dom.js?v=14';

const $=id=>document.getElementById(id),text=(tag,value,cls)=>safeTextElement(document,tag,value,cls);
function setMode(mode,focus=false){for(const tab of document.querySelectorAll('[role=tab]')){const active=tab.dataset.mode===mode;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;$(tab.getAttribute('aria-controls')).hidden=!active;if(active&&focus)tab.focus()}const url=new URL(location.href);if(mode==='references')url.searchParams.delete('mode');else url.searchParams.set('mode',mode);history.replaceState(null,'',url)}
for(const tab of document.querySelectorAll('[role=tab]'))tab.onclick=()=>setMode(tab.dataset.mode);
document.querySelector('.tabs').onkeydown=event=>{const tabs=[...document.querySelectorAll('[role=tab]')],i=tabs.indexOf(document.activeElement);if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:event.key==='ArrowRight'?(i+1)%tabs.length:(i-1+tabs.length)%tabs.length;setMode(tabs[next].dataset.mode,true)};
function analyseReferences(){const box=$('reference-results'),input=$('reference-input').value;try{const parsed=parseInput(input,globalThis.Cite),duplicates=findDuplicates(parsed.records),byIndex=new Map(duplicates.flatMap(group=>group.indexes.map(index=>[index,group.reason])));box.replaceChildren(...parsed.records.map((record,index)=>{const card=text('article','', 'result');card.append(text('h3',record.title||record.DOI||`Reference ${index+1}`),text('p',record.DOI?`DOI: ${record.DOI}`:'No DOI detected','meta'),text('p',byIndex.get(index)||'No exact normalized DOI duplicate detected',byIndex.has(index)?'bad':'good'));return card}));$('reference-status').textContent=`Parsed ${parsed.records.length} reference${parsed.records.length===1?'':'s'}; ${duplicates.length} duplicate group${duplicates.length===1?'':'s'} flagged.`}catch(error){box.replaceChildren();$('reference-status').textContent=`Could not parse the input: ${error.message}`}}
$('reference-analyse').onclick=analyseReferences;$('reference-example').onclick=()=>{$('reference-input').value='10.1038/nature12373\n10.1038/nature12373\n10.1371/journal.pone.0000308';analyseReferences()};$('reference-clear').onclick=()=>{$('reference-input').value='';$('reference-results').replaceChildren();$('reference-status').textContent='Cleared.'};
function evidenceLink(item){const link=text('a',item.type==='issn'?'Open in Journal Hub':'Open primary record');if(item.type==='issn')link.href=`/tools/journal-hub/?q=${encodeURIComponent(item.normalized)}&journal=${encodeURIComponent(item.normalized)}`;else if(item.type==='doi')link.href=`https://doi.org/${encodeURIComponent(item.normalized)}`;else if(item.type==='orcid')link.href=`https://orcid.org/${encodeURIComponent(item.normalized)}`;else return null;if(link.href.startsWith('http')){link.target='_blank';link.rel='noopener noreferrer'}return link}
function analyseIdentifiers(){const items=detectIdentifiers($('identifier-input').value),box=$('identifier-results');box.replaceChildren(...items.map(item=>{const card=text('article','', 'result');card.append(text('h3',item.type.toUpperCase()),text('p',item.normalized||item.raw,'meta'),text('p',item.valid?'Structure/checksum valid':'Invalid structure or checksum',item.valid?'good':'bad'));const link=item.valid&&evidenceLink(item);if(link)card.append(link);return card}));$('identifier-status').textContent=`Detected ${items.length} identifier${items.length===1?'':'s'}; ${items.filter(item=>item.valid).length} passed local validation.`}
$('identifier-analyse').onclick=analyseIdentifiers;$('identifier-example').onclick=()=>{$('identifier-input').value='10.1038/s41586-020-2649-2\nISSN 2049-3630\nORCID 0000-0002-1825-0097\nISBN 978-0-306-40615-7';analyseIdentifiers()};$('identifier-clear').onclick=()=>{$('identifier-input').value='';$('identifier-results').replaceChildren();$('identifier-status').textContent='Cleared.'};
setMode(new URLSearchParams(location.search).get('mode')==='identifiers'?'identifiers':'references');
