const data=window.JOURNAL_TIMING_DATA||[],coverage=window.JOURNAL_TIMING_COVERAGE||{};
const $=id=>document.getElementById(id);let sort={key:'j',direction:1},visible=[];
const metric=(row,key)=>row.x?.[key]?.median??null;const escapeCsv=value=>`"${String(value??'').replaceAll('"','""')}"`;
function evidence(row){const span=document.createElement('span');const links=[];if(row.x){const a=document.createElement('a');a.href=`https://api.crossref.org/journals/${encodeURIComponent(row.x.issn||row.i[0])}/works`;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Crossref';links.push(a)}if(row.du){const a=document.createElement('a');a.href=row.du;a.target='_blank';a.rel='noopener noreferrer';a.textContent='DOAJ';links.push(a)}links.forEach((a,i)=>{if(i)span.append(' · ');span.append(a)});return span}
function value(row,key){if(key==='j')return row.j.toLowerCase();if(key==='dw')return row.dw??Infinity;if(key==='n')return row.x?.n??0;return metric(row,{sa:'submit_accept',ao:'accept_online',so:'submit_online'}[key])??Infinity}
function filters(){const q=$('query').value.trim().toLowerCase(),subject=$('subject').value,min=Number($('minimum').value)||0;visible=data.filter(row=>(!q||`${row.j} ${row.i.join(' ')}`.toLowerCase().includes(q))&&(!subject||row.s===subject)&&(!$('oa').checked||row.oa)&&(!$('has-data').checked||row.dw!=null||row.x?.n>0)&&(row.x?.n||0)>=min);visible.sort((a,b)=>{const x=value(a,sort.key),y=value(b,sort.key);return (typeof x==='string'?x.localeCompare(y):x-y)*sort.direction});render()}
function td(text,className=''){const cell=document.createElement('td');cell.textContent=text;cell.className=className;return cell}
function render(){const body=$('rows');body.replaceChildren();for(const row of visible){const tr=document.createElement('tr'),total=row.x?.submit_online,iqr=total?.iqr;const title=td(row.j);const link=document.createElement('a');link.href=`/tools/emerging-journals-2026/?q=${encodeURIComponent(row.j)}`;link.textContent=row.j;title.replaceChildren(link);tr.append(title,td(row.p||'—'),td(row.dw??'—'),td(metric(row,'submit_accept')??'—'),td(metric(row,'accept_online')??'—'),td(metric(row,'submit_online')??'—'),td(iqr?`${iqr[0]}–${iqr[1]}`:'—'),td(row.x?.n??0),td('Not openly available'));const source=td('');source.append(evidence(row));tr.append(source,td(coverage.retrieved||'—'));body.append(tr)}document.querySelectorAll('th[aria-sort]').forEach(header=>header.setAttribute('aria-sort',header.querySelector(`[data-sort="${sort.key}"]`)?(sort.direction===1?'ascending':'descending'):'none'));const direction=sort.direction===1?'ascending':'descending';$('status').textContent=`${visible.length} journal${visible.length===1?'':'s'} shown, sorted ${direction}.`;$('emerging-link').href=`/tools/emerging-journals-2026/?q=${encodeURIComponent($('query').value.trim())}`}
function download(){const head=['Journal','Publisher','ISSNs','Subject','DOAJ weeks','Submit to accept median days','Accept to online median days','Total median days','Total IQR','n','Acceptance rate','Last updated'];const lines=[head,...visible.map(r=>[r.j,r.p,r.i.join('; '),r.s,r.dw??'',metric(r,'submit_accept')??'',metric(r,'accept_online')??'',metric(r,'submit_online')??'',r.x?.submit_online?.iqr?.join('-')??'',r.x?.n??0,'Not openly available',coverage.retrieved||''])].map(row=>row.map(escapeCsv).join(','));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='journal-timing.csv';a.click();URL.revokeObjectURL(a.href)}
for(const subject of [...new Set(data.map(x=>x.s))].sort()){const option=document.createElement('option');option.value=option.textContent=subject;$('subject').append(option)}
for(const id of ['query','subject','minimum','oa','has-data'])$(id).addEventListener(id==='query'?'input':'change',filters);document.querySelectorAll('[data-sort]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.sort;sort={key,direction:sort.key===key?-sort.direction:1};filters()}));$('download').addEventListener('click',download);$('example').addEventListener('click',()=>{$('query').value='Plant Journal';filters()});
const params=new URLSearchParams(location.search);if(params.get('q'))$('query').value=params.get('q');if(params.get('example')==='1')$('query').value='Plant Journal';$('coverage').textContent=`Snapshot: ${coverage.journals_attempted||0} journals attempted; ${coverage.journals_with_crossref_timing||0} with Crossref timing; ${coverage.journals_with_doaj_weeks||0} with DOAJ weeks.`;filters();
