import{summarize}from'./src/summary.js?v=25';
const coverage=window.JOURNAL_TIMING_COVERAGE||{},$=id=>document.getElementById(id),CACHE_PREFIX='smbajwa.timing.',CACHE_TTL=30*86400000;
let manifest={subjects:[],examples:[]},loaded=[],visible=[],sort={key:'j',direction:1},searchToken=0,liveBusy=false,lastLiveStart=0;
const shardCache=new Map(),titleCache=new Map();
const normalizeIssn=value=>{const x=String(value||'').replace(/[^0-9X]/gi,'').toUpperCase();return /^\d{7}[\dX]$/.test(x)?`${x.slice(0,4)}-${x.slice(4)}`:null};
const titleKey=value=>(String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,2)||'__').padEnd(2,'_');
const shaKey=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-1',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,2);
async function json(path){const response=await fetch(path);if(!response.ok)throw new Error(`Data request failed (${response.status})`);return response.json();}
async function shardFor(issn){const key=await shaKey(issn);if(!shardCache.has(key))shardCache.set(key,json(`data/shards/${key}.json`));return shardCache.get(key);}
async function recordFor(issn){const payload=await shardFor(issn),canonical=payload.a?.[issn]||issn;if(canonical!==issn)return recordFor(canonical);return payload.r?.find(row=>row.i.includes(issn))||null;}
async function search(){const token=++searchToken,query=$('query').value.trim(),issn=normalizeIssn(query);$('search-error').textContent='';if(!query){loaded=[];filters();return;}try{let rows=[];if(issn){const row=await recordFor(issn);if(row)rows=[row];}else if(query.replace(/[^a-z0-9]+/gi,'').length>=2){const key=titleKey(query);if(!titleCache.has(key))titleCache.set(key,json(`data/titles/${key}.json`));const matches=(await titleCache.get(key)).filter(([title])=>title.toLowerCase().includes(query.toLowerCase())).slice(0,50);rows=(await Promise.all(matches.map(([,id])=>recordFor(id)))).filter(Boolean);}if(token!==searchToken)return;loaded=[...new Map(rows.map(row=>[row.i[0],row])).values()];filters();}catch(error){if(token===searchToken){loaded=[];filters();$('search-error').textContent=error.message;}}}
const metric=(row,key)=>row.x?.[key]?.median??null;
function value(row,key){if(key==='j')return row.j.toLowerCase();if(key==='dw')return row.dw??Infinity;if(key==='n')return row.x?.n??0;return metric(row,{sa:'submit_accept',ao:'accept_online',so:'submit_online'}[key])??Infinity;}
function filters(){const subject=$('subject').value,min=Number($('minimum').value)||0,source=$('source').value,recency=Number($('recency').value)||0;visible=loaded.filter(row=>(!subject||row.s===subject)&&(!$('oa').checked||row.oa)&&(!$('has-data').checked||row.dw!=null||row.x?.n>0)&&(row.x?.n||0)>=min&&(!source||(source==='crossref'?row.x?.n>0:row.dw!=null))&&(!recency||Date.parse(row.x?.retrieved||row.dr||0)>=Date.now()-recency*86400000));visible.sort((a,b)=>{const x=value(a,sort.key),y=value(b,sort.key);return(typeof x==='string'?x.localeCompare(y):x-y)*sort.direction;});render();}
function td(text){const cell=document.createElement('td');cell.textContent=text;return cell;}
function button(text,handler){const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',handler);return b;}
function evidence(row){const span=document.createElement('span'),links=[];if(row.x){const a=document.createElement('a');a.href=`https://api.crossref.org/journals/${encodeURIComponent(row.x.issn||row.i[0])}/works`;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Crossref';links.push(a);}if(row.du){const a=document.createElement('a');a.href=row.du;a.target='_blank';a.rel='noopener noreferrer';a.textContent='DOAJ';links.push(a);}links.forEach((a,i)=>{if(i)span.append(' · ');span.append(a);});return span;}
function render(){const body=$('rows');body.replaceChildren();for(const row of visible.slice(0,50)){const tr=document.createElement('tr'),title=td('');title.append(button(row.j,()=>showDetail(row)));tr.append(title,td(row.i.join(', ')),td(row.s),td(row.dw??'—'),td(metric(row,'submit_online')??'—'),td(row.x?.n??0));const detail=td('');detail.append(button('View details',()=>showDetail(row)));tr.append(detail);body.append(tr);}document.querySelectorAll('th[aria-sort]').forEach(header=>header.setAttribute('aria-sort',header.querySelector(`[data-sort="${sort.key}"]`)?(sort.direction===1?'ascending':'descending'):'none'));$('status').textContent=`${visible.length} loaded journal${visible.length===1?'':'s'} shown${loaded.length>=50?' (first 50 matches)':''}, sorted ${sort.direction===1?'ascending':'descending'}.`;$('emerging-link').href=`/tools/emerging-journals-2026/?q=${encodeURIComponent($('query').value.trim())}`;}
const line=(label,value)=>{const p=document.createElement('p'),strong=document.createElement('strong');strong.textContent=`${label}: `;p.append(strong,String(value??'—'));return p;};
function showDetail(row,live=null){const panel=$('detail');panel.hidden=false;panel.replaceChildren();const heading=document.createElement('h2');heading.textContent=row.j;panel.append(heading,line('ISSNs',row.i.join(', ')),line('Publisher',row.p||'—'),line('Subject',row.s),line('DOAJ stated submission-to-publication weeks',row.dw??'Unavailable'));const x=live||row.x;if(x){panel.append(line('Submit → accept median',x.submit_accept.median==null?'Unavailable':`${x.submit_accept.median} days (IQR ${x.submit_accept.iqr?.join('–')||'suppressed'}; n=${x.submit_accept.n})`),line('Accept → online median',x.accept_online.median==null?'Unavailable':`${x.accept_online.median} days (IQR ${x.accept_online.iqr?.join('–')||'suppressed'}; n=${x.accept_online.n})`),line('Total median',x.submit_online.median==null?'Unavailable':`${x.submit_online.median} days (IQR ${x.submit_online.iqr?.join('–')||'suppressed'}; n=${x.submit_online.n})`),line('Sampled works with any interval',x.n),line('Publication years',x.years?.join('–')||'Unavailable'),line('Window',x.window?.join(' to ')||'Recent three-year window'),line(live?'Live from Crossref, retrieved':'Snapshot retrieved',x.retrieved||coverage.retrieved||'—'));}else panel.append(line('Crossref snapshot','Unavailable'));const sources=document.createElement('p');sources.append('Evidence: ',evidence(row));panel.append(sources);const liveButton=button('Look up recent Crossref dates now',()=>lookupLive(row,liveButton));liveButton.className='primary-action';panel.append(liveButton);const notice=document.createElement('p');notice.className='network-notice';notice.textContent='This sends only the selected ISSN to api.crossref.org when you click the button.';panel.append(notice);const message=document.createElement('p');message.id='live-status';message.setAttribute('role','status');message.setAttribute('aria-live','polite');panel.append(message);panel.scrollIntoView({block:'nearest'});}
function cached(issn){try{const item=JSON.parse(localStorage.getItem(CACHE_PREFIX+issn));return item&&Date.now()-item.saved<CACHE_TTL?item.value:null;}catch{return null;}}
function saveCache(issn,value){try{localStorage.setItem(CACHE_PREFIX+issn,JSON.stringify({saved:Date.now(),value}));}catch{}}
async function lookupLive(row,control){if(liveBusy)return;const issn=row.i[0],prior=cached(issn);if(prior){showDetail(row,prior);$('live-status').textContent='Loaded a live Crossref result cached in this browser.';return;}liveBusy=true;control.disabled=true;const pause=Math.max(0,5000-(Date.now()-lastLiveStart));$('live-status').textContent=pause?'Waiting briefly before contacting Crossref…':'Contacting Crossref…';if(pause)await new Promise(resolve=>setTimeout(resolve,pause));lastLiveStart=Date.now();$('live-status').textContent='Contacting Crossref…';const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),30000);try{const start=new Date(Date.now()-1096*86400000).toISOString().slice(0,10),params=new URLSearchParams({filter:`from-pub-date:${start},type:journal-article`,rows:'300',select:'assertion,published,published-online'}),response=await fetch(`https://api.crossref.org/journals/${encodeURIComponent(issn)}/works?${params}`,{signal:abort.signal});if(response.status===404)throw new Error('This ISSN is not in Crossref.');if(!response.ok)throw new Error(`Crossref returned ${response.status}. Please try again later.`);const summary=summarize((await response.json()).message?.items||[]),today=new Date().toISOString().slice(0,10);Object.assign(summary,{source:'Crossref',retrieved:today,window:[start,today],issn});saveCache(issn,summary);showDetail(row,summary);$('live-status').textContent='Live lookup complete.';}catch(error){$('live-status').textContent=error.name==='AbortError'?'Crossref did not respond within 30 seconds.':error.message||'The Crossref lookup failed. Please try again.';}finally{clearTimeout(timer);liveBusy=false;control.disabled=false;}}
function clearCache(){try{for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith(CACHE_PREFIX))localStorage.removeItem(key);}$('status').textContent='Journal Timing live lookup cache cleared.';}catch{$('status').textContent='Local storage is unavailable; no cache was changed.';}}
function download(){const head=['Journal','Publisher','ISSNs','Subject','DOAJ weeks','Submit to accept median days','Accept to online median days','Total median days','Total IQR','n','Last updated'],quote=value=>`"${String(value??'').replaceAll('"','""')}"`,lines=[head,...visible.map(r=>[r.j,r.p,r.i.join('; '),r.s,r.dw??'',metric(r,'submit_accept')??'',metric(r,'accept_online')??'',metric(r,'submit_online')??'',r.x?.submit_online?.iqr?.join('-')??'',r.x?.n??0,r.x?.retrieved||r.dr||''])].map(row=>row.map(quote).join(','));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download='journal-timing-loaded-filtered.csv';a.click();URL.revokeObjectURL(a.href);}
let debounce;for(const id of ['subject','minimum','oa','has-data','source','recency'])$(id).addEventListener(id==='minimum'?'input':'change',filters);$('query').addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(search,180);});document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.sort;sort={key,direction:sort.key===key?-sort.direction:1};filters();}));$('download').addEventListener('click',download);$('clear-cache').addEventListener('click',clearCache);
async function init(){manifest=await json('data/manifest.json');for(const subject of manifest.subjects){const option=document.createElement('option');option.value=option.textContent=subject;$('subject').append(option);}const examples=$('examples');for(const [title] of manifest.examples)examples.append(button(title,()=>{$('query').value=title;search();}));const params=new URLSearchParams(location.search);if(params.get('q'))$('query').value=params.get('q');if(params.get('example')==='1')$('query').value=manifest.examples[0]?.[0]||'Plant Journal';$('coverage').textContent=`Index: ${manifest.journals||coverage.joinable_issn_journals||0} ISSN-joinable journals; snapshot has ${coverage.journals_with_crossref_timing||0} Crossref summaries and ${coverage.journals_with_doaj_weeks||0} DOAJ values.`;if($('query').value)search();else filters();}
init().catch(error=>$('search-error').textContent=error.message);
